
services:
    # captcha type
    captcha.type:
        class: Gregwar\CaptchaBundle\Type\CaptchaType
        arguments: [@session, %gregwar_captcha.image.width%, %gregwar_captcha.image.height%]
        tags:
            - { name: form.type, alias: captcha }
