
services:
    # captcha type
    captcha.type:
        class: Gregwar\CaptchaBundle\Type\CaptchaType
        arguments: [@session, %gregwar_captcha.width%, %gregwar_captcha.height%, %gregwar_captcha.length%]
        tags:
            - { name: form.type, alias: captcha }
